[WIP]: Adding the multi-account functionality
harness/backstage-plugins pull request #77
Opened 2023-03-24 11:30 UTC by Debanitrkl

## Describe your changes
This adds the feature to use multiple accounts in a single backstage instance. 
## Checklist
- [ ] I've documented the changes in the PR description.
- [ ] I've tested this change either in PR or local environment.

## [Contributor license agreement](https://github.com/harness/backstage-plugins/blob/main/Contributor_License_Agreement.md)

2023-03-27 10:02 UTC, SarvJ1 commented on app-config.yaml
> +      'x-api-key': ${HARNESS_API_KEY}
If you could rename the Environment Variables Names, would be better to inject them later

2023-03-29 07:04 UTC, Debanitrkl commented
@Ompragash here's the changes, it's now able to display pipelines from [multiple accounts](https://github.com/harness/backstage-plugins/pull/77/files) with different hostname in a single backstage instance.
Here's a screenshot of CI/CD plugin displaying pipelines for a [project](https://stage.harness.io/ng/#/account/wFHXHD0RRQWoO8tIZT5YVw/home/orgs/Harness/projects/RELEASEBUILDS/) in [stage.harness.io](https://stage.harness.io/)
<img width="1728" alt="Screenshot 2023-03-29 at 12 25 13 PM" src="https://user-images.githubusercontent.com/50622005/228452141-32d9064e-a03c-4e2e-8ff1-ee4face7b8a9.png">

Also, for the documentation, I don't think we should change anything because this is just for an internal use case and doesn't change anything with the the way you should set-up the plugin inside your backstage instance.

2023-03-30 03:42 UTC, sandeepa-kv-jois reviewed
It's not supporting multiple accounts within same host/env, essentially more than one x-api-key. Are we planning this effort separately?

2023-04-05 06:19 UTC, jenil-harness requested changes

2023-04-05 06:19 UTC, jenil-harness commented on plugins/harness-ci-cd/src/components/ExecutionList/ExecutionList.tsx
>      const value = token ? `Bearer ${token}` : '';
`getSecureHarnessKey` will return in format `Bearer ${token}`. We are adding Bearer again.

2023-04-05 06:19 UTC, jenil-harness commented on plugins/harness-ci-cd/src/components/ExecutionList/ExecutionList.tsx
> +      const token = JSON.parse(
Please consider using Prettier.

2023-04-06 16:49 UTC, Ompragash approved these changes

2023-04-06 17:21 UTC, merged